### PR TITLE
Improve terraform provider docs visibility

### PR DESCRIPTION
**Pull request by brittandeyoung**
*Issue #, if available:*
 Closes: #181

*Description of changes:*
This change improves the visibility of the terraform provider through documentation updates by:
1. Mentioning the provider in the Readme quick links
2. Moving the provider docs to its own navigation item. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by robbycuenot** [comment]
Hey @brittandeyoung , I'd love to test this out. I'll give it a shot on my personal org sometime in the next week or two. Not sure what your thoughts are on merging this into the official aws-samples org, but I know my company would be far more likely to use this if it resides in an aws-owned repo. I've also considered directly managing the eligibility / approver policies using the standard aws provider. Great work, looking forward to trying it!

**Comment by brittandeyoung** [comment]
@robbycuenot Great, please test and report any issues to the provider repo. 

I would be fine with the provider becoming an official aws-sample at some point and help manage it. But as I am not a AWS employee, I am not sure what that process would look like, or if it is even possible. This would likely be a question for @tawoyinfa

**Comment by robbycuenot** [comment]
@brittandeyoung , have you found any extra logic around creating eligibility / approver policies, aside from updating the DynamoDB tables?

I'm slating a backlog item for my team to try managing these with the official aws provider and dynamo. In theory, one should be able to manage these policies, and the app admin settings, using TF like this:

```terraform
data "aws_dynamodb_table" "example" {
 name           = "example-name"
 read_capacity  = 10
 write_capacity = 10
 hash_key       = "exampleHashKey"
 attribute {
   name = "exampleHashKey"
   type = "S"
 }
}

resource "aws_dynamodb_table_item" "example" {
 table_name = data.aws_dynamodb_table.example.name
 hash_key   = data.aws_dynamodb_table.example.hash_key
 item = <<ITEM
{
 "id": "98765432-9876-9876-9876-987654321098",
 "accounts": [
  {
   "id": "012345678901",
   "name": "example-account"
  }
 ],
 "approvalRequired": true,
 "createdAt": "2024-02-12T18:55:23.301Z",
 "duration": "24",
 "modifiedBy": "idc_admin@example.com",
 "name": "Example-Eligibility-Policy-Name",
 "ous": [
 ],
 "permissions": [
  {
   "id": "arn:aws:sso:::permissionSet/ssoins-0123456789012345/ps-0123456789012345",
   "name": "TEAM-ExampleAccess"
  }
 ],
 "ticketNo": "",
 "type": "Group",
 "updatedAt": "2024-02-13T21:47:01.981Z",
 "__typename": "Eligibility"
}
ITEM
}
```

Creating an internal module that emulates what you're doing in the provider would make it cleaner for sure. Just thinking of stop-gap solutions that don't require third-party dependencies

**Comment by robbycuenot** [comment]
I'm sure the architecture docs cover this in some form, but I had chatgpt spit out a sequence diagram and it sounds like my previous comment should work, at least for eligibility policies

```mermaid
sequenceDiagram
    participant User as User
    participant UI as Amplify App UI
    participant RS as RequestService.js
    participant API as GraphQL API
    participant DB as DynamoDB

    User->>UI: Submits new eligibility policy form
    UI->>RS: Calls addPolicy(data)
    RS->>API: Executes createEligibility mutation
    alt Successful request
        API->>DB: Stores new policy in DynamoDB
        DB->>API: Returns success response with policy ID
        API->>RS: Returns policy ID
        RS->>UI: Displays success message / Uses policy ID
    else Error occurred
        API->>RS: Returns error
        RS->>UI: Displays error message
    end
```

**Comment by brittandeyoung** [comment]
@robbycuenot  I can't speak to how you would do this outside of the provider. The provider interacts directly with the API to create and manage the resources.

**Comment by robbycuenot** [comment]
> @robbycuenot I can't speak to how you would do this outside of the provider. The provider interacts directly with the API to create and manage the resources.

No worries -- I've searched through your codebase and honestly doing it through your provider seems to be the smarter approach. If this can gain official support, I am very eager to use it professionally

**Pull request closed without merging**
