### PR TITLE
Feature: Enable Machine Authentication to access Graph API Mutations

### PR DESCRIPTION
**Pull request by brittandeyoung**
*Issue #, if available:*
Closes: #33 

*Description of changes:*

This PR implements the following:
1. A script to automate the creation of the needed resources to enable machine authentication on the Cognito User pool: 
- Resource Server with a custom scope of `admin`
- User Pool Client with client secret generation enabled along with the other needed items for machine auth flows and assigned the `api/admin` custom scope.
2. Adds and `auth` rule on each mutation which currently allows full access to members of the `admin` group that grants the same level of access to machine authentication which uses the `api/admin` custom scope. 

I have tested these in or TEAM test environment and validated that I am able to perform the following:
1. Use the client_id and client_secret to obtain a token using the cognito user pool token endpoint.
2. Use this token to perform all queries.
3. Use this token to perform mutations on the `Settings`, `Approvers`, and `Eligibility` types. 

This work will further enable a terraform provider I have been writing for managing AWS TEAM. As this is my first contribution, please let me know if there is anything I am missing.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tawoyinfa** [comment]
@brittandeyoung  thanks for leading on this. I would review and merge once tested

**Comment by brittandeyoung** [comment]
> @brittandeyoung thanks for leading on this. I would review and merge once tested

@tawoyinfa For clarification. Are you requesting that I perform some testing? or are you stating that you will be doing some testing? 

I have this currently deployed to my testing environment and it is behaving as expected.

**Comment by tawoyinfa** [comment]
@brittandeyoung  I am doing some internal testing. Thanks again for this

**Comment by tawoyinfa** [comment]
@brittandeyoung  tested and works well. Feature has now been merged. Thanks again for putting in the work

**Comment by robbycuenot** [comment]
Hey @tawoyinfa , I see a placeholder for the tf code but this issue should probably be reopened for visibility, so that you don't get duplicate requests. Thanks!

**Pull request merged**
